#!/bin/sh

MAINTAINER_INFO="Liran Oz <lirano@mellanox.com>"

gen_changelog_in()
{
cat > $1 << eOf
libvma (@VERSION@-@VMA_LIBRARY_RELEASE@) release; urgency=low

  * Please refer to journal.txt for full changelog.

 -- ${MAINTAINER_INFO}  $(date +'%a, %d %b %Y %T %z')
eOf
}

if test -n "$1" ; then
  gen_changelog_in "$1"
fi
