#!/bin/bash

/etc/init.d/vma stop || true
if [ -e /sbin/chkconfig ]; then
    /sbin/chkconfig --del vma || true
elif [ -e /usr/sbin/update-rc.d ]; then
    /usr/sbin/update-rc.d -f vma remove || true
else
    /usr/lib/lsb/remove_initd /etc/init.d/vma || true
fi
if type systemctl >/dev/null 2>&1; then
    systemctl --system daemon-reload || true
fi
