
/* Line 3 of config_scanner.c */

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer libvma_yy_create_buffer
#define yy_delete_buffer libvma_yy_delete_buffer
#define yy_flex_debug libvma_yy_flex_debug
#define yy_init_buffer libvma_yy_init_buffer
#define yy_flush_buffer libvma_yy_flush_buffer
#define yy_load_buffer_state libvma_yy_load_buffer_state
#define yy_switch_to_buffer libvma_yy_switch_to_buffer
#define yyin libvma_yyin
#define yyleng libvma_yyleng
#define yylex libvma_yylex
#define yylineno libvma_yylineno
#define yyout libvma_yyout
#define yyrestart libvma_yyrestart
#define yytext libvma_yytext
#define yywrap libvma_yywrap
#define yyalloc libvma_yyalloc
#define yyrealloc libvma_yyrealloc
#define yyfree libvma_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE libvma_yyrestart(libvma_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t libvma_yyleng;

extern FILE *libvma_yyin, *libvma_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up libvma_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up libvma_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via libvma_yyrestart()), so that the user can continue scanning by
	 * just pointing libvma_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when libvma_yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t libvma_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow libvma_yywrap()'s to do buffer switches
 * instead of setting up a fresh libvma_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void libvma_yyrestart (FILE *input_file  );
void libvma_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE libvma_yy_create_buffer (FILE *file,int size  );
void libvma_yy_delete_buffer (YY_BUFFER_STATE b  );
void libvma_yy_flush_buffer (YY_BUFFER_STATE b  );
void libvma_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void libvma_yypop_buffer_state (void );

static void libvma_yyensure_buffer_stack (void );
static void libvma_yy_load_buffer_state (void );
static void libvma_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER libvma_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE libvma_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE libvma_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE libvma_yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *libvma_yyalloc (yy_size_t  );
void *libvma_yyrealloc (void *,yy_size_t  );
void libvma_yyfree (void *  );

#define yy_new_buffer libvma_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        libvma_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            libvma_yy_create_buffer(libvma_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        libvma_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            libvma_yy_create_buffer(libvma_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *libvma_yyin = (FILE *) 0, *libvma_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int libvma_yylineno;

int libvma_yylineno = 1;

extern char *libvma_yytext;
#define yytext_ptr libvma_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up libvma_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	libvma_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[614] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       32,   30,   29,   27,   28,    5,    5,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   29,    1,   24,
       24,    5,    5,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,   26,   26,    5,    5,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,    1,   29,
       28,    5,    0,    0,    0,    0,    0,   15,   18,    0,

        0,    0,    0,    0,    0,    0,    0,   29,    1,    1,
       24,   24,    5,   24,   24,   24,   24,   24,   15,   18,
       24,   24,   24,   24,   24,   24,   24,   24,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,   26,   26,    5,
       26,   26,   26,   26,   26,   15,   18,   26,   26,   26,
       26,   26,   26,   26,   26,    1,    0,    0,    0,    6,
        0,   17,    0,   13,   14,   12,   16,    0,    0,    1,

       24,   24,   24,    6,   24,   17,   24,   13,   14,   12,
       16,   24,   24,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,   26,
       26,   26,    6,   26,   17,   26,   13,   14,   12,   16,
       26,   26,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   24,   24,   24,   24,   24,   24,   24,   24,   24,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,   26,   26,
       26,   26,   26,   26,   26,   26,   26,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   11,    0,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   11,
       24,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   11,   26,    0,   25,    0,
        0,   10,    0,    0,    0,    0,    0,    0,   24,   24,
       24,   24,   10,   24,   24,   24,   24,   24,   24,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,

        4,   26,   25,   26,   26,   10,   26,   26,   26,   26,
       26,   26,    0,    0,    0,    0,    0,    0,    0,    0,
        9,   24,   24,   24,   24,   24,   24,   24,   24,    9,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,   26,   26,
       26,   26,   26,   26,   26,   26,    9,    0,    0,    0,
        0,    0,    0,    0,    0,   24,   24,   24,   24,   24,
       24,   24,   24,    3,    3,    3,    3,    3,    3,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,   26,
       26,   26,   26,   26,   26,   26,   26,    0,    0,    8,

        0,    0,    0,    0,    0,   24,   24,    8,   24,   24,
       24,   24,   24,    3,    3,    3,    3,    3,    3,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,   26,
       26,    8,   26,   26,   26,   26,   26,    0,    0,   19,
       20,    0,    0,   21,   24,   24,   19,   20,   24,   24,
       21,    3,    3,    3,    3,    3,    3,    3,    4,    4,
        4,    4,    4,    4,    4,   26,   26,   19,   20,   26,
       26,   21,    0,    7,   23,    0,   24,    7,   23,   24,
        3,    3,    3,    3,    4,    4,    4,    4,   26,    7,
       23,   26,    0,   22,   24,   22,    3,    3,    4,    4,

       26,   22,    0,   24,    3,    4,   26,    2,    2,    2,
        2,    2,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    1,    1,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,    1,    9,    1,   10,   11,

       12,   13,   14,    1,   15,    1,    1,   16,   17,   18,
       19,   20,    1,   21,   22,   23,   24,   25,    1,    1,
       26,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[27] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[629] =
    {   0,
        0,   25,   29,   54,   58,   83,   87,  112,  116,  141,
      709,  710,  706,  710,    0,  710,  140,  687,  139,  687,
      690,  682,  141,  693,  133,  685,  136,  152,    0,    0,
      699,    0,  153,  680,  152,  680,  683,  675,  154,  686,
      146,  678,  140,  692,    0,  691,    0,  163,  672,  162,
      672,  675,  667,  164,  678,  155,  670,  159,  684,    0,
      683,    0,  172,  664,  173,  664,  667,  659,  175,  670,
      165,  662,  170,  676,    0,  675,    0,  182,  656,  182,
      656,  659,  651,  184,  662,  185,  654,  184,  668,  667,
        0,  192,  648,  655,  644,  651,  646,  710,  710,  643,

      640,  641,  640,  647,  649,  642,  633,  198,    0,    0,
        0,  653,  197,  634,  641,  630,  637,  632,    0,    0,
      629,  626,  627,  626,  633,  635,  628,  619,  639,    0,
      638,  202,  619,  626,  615,  622,  617,    0,    0,  614,
      611,  612,  611,  618,  620,  613,  604,  624,    0,  623,
      205,  604,  611,  600,  607,  602,    0,    0,  599,  596,
      597,  596,  603,  605,  598,  589,  609,    0,  608,  207,
      589,  596,  585,  592,  587,    0,    0,  584,  581,  582,
      581,  588,  590,  583,  574,  594,  579,  577,  570,  710,
      587,  710,  575,  582,  581,  710,  710,  572,  576,    0,

      570,  568,  561,    0,  578,    0,  566,  573,  572,    0,
        0,  563,  567,  561,  559,  552,    0,  569,    0,  557,
      564,  563,    0,    0,  554,  558,  552,  550,  543,    0,
      560,    0,  548,  555,  554,    0,    0,  545,  549,  543,
      541,  534,    0,  551,    0,  539,  546,  545,    0,    0,
      536,  540,  535,  530,  533,  531,  527,  195,  205,  533,
      532,  528,  523,  526,  524,  520,  206,  208,  526,  525,
      521,  516,  519,  517,  513,  209,  211,  519,  518,  514,
      509,  512,  510,  506,  212,  214,  512,  511,  507,  502,
      505,  503,  499,  215,  228,  505,  504,  505,  496,  495,

      500,  497,  494,  497,  489,  495,  494,  710,  484,  494,
      485,  484,  489,  486,  483,  486,  478,  484,  483,    0,
      473,  483,  474,  473,  478,  475,  472,  475,  467,  473,
      472,    0,  462,  472,  463,  462,  467,  464,  461,  464,
      456,  462,  461,    0,  451,  461,  452,  451,  456,  453,
      450,  453,  445,  451,  450,    0,  440,  451,  710,  450,
      433,  710,  442,  435,  437,  444,  435,  431,  442,    0,
      441,  424,    0,  433,  426,  428,  435,  426,  422,  433,
        0,  432,  415,    0,  424,  417,  419,  426,  417,  413,
      424,    0,  423,  406,    0,  415,  408,  410,  417,  408,

      404,  415,    0,  414,  397,    0,  406,  399,  401,  408,
      399,  395,  392,  391,  401,  400,  386,  392,  397,  397,
      710,  384,  383,  393,  392,  378,  384,  389,  389,    0,
      376,  375,  385,  384,  370,  376,  381,  381,    0,  368,
      367,  377,  376,  362,  368,  373,  373,    0,  360,  359,
      369,  368,  354,  360,  365,  365,    0,  360,  359,  357,
      354,  359,  358,  354,  356,  352,  351,  349,  346,  351,
      350,  346,  348,  344,  343,  341,  338,  343,  342,  338,
      340,  336,  335,  333,  330,  335,  334,  330,  332,  328,
      327,  325,  322,  327,  326,  322,  324,  316,  315,  710,

      310,  311,  321,  305,  308,  309,  308,    0,  303,  304,
      314,  298,  301,  302,  301,    0,  296,  297,  307,  291,
      294,  295,  294,    0,  289,  290,  300,  284,  287,  288,
      287,    0,  282,  283,  293,  277,  280,  282,  281,  710,
      710,  275,  285,  710,  278,  277,    0,    0,  271,  281,
        0,  274,  273,    0,    0,  267,  277,    0,  270,  269,
        0,    0,  263,  273,    0,  266,  265,    0,    0,  259,
      269,    0,  275,  710,  710,  258,  273,    0,    0,  256,
      271,    0,    0,  254,  269,    0,    0,  252,  243,    0,
        0,  226,  231,  710,  230,    0,  229,    0,  228,    0,

      227,    0,  230,  229,  228,  212,  209,  710,    0,    0,
        0,    0,  710,  250,  252,  114,  254,  256,   85,  258,
      260,   56,  262,  264,   27,  266,  268,  270
    } ;

static yyconst flex_int16_t yy_def[629] =
    {   0,
      613,    1,  613,    3,  613,    5,  613,    7,  613,    9,
      613,  613,  613,  613,  614,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  615,  616,
      617,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      616,  616,  616,  618,  619,  620,  619,  619,  619,  619,
      619,  619,  619,  619,  619,  619,  619,  619,  621,  622,
      623,  622,  622,  622,  622,  622,  622,  622,  622,  622,
      622,  622,  622,  624,  625,  626,  625,  625,  625,  625,
      625,  625,  625,  625,  625,  625,  625,  625,  627,  613,
      614,  613,  613,  613,  613,  613,  613,  613,  613,  613,

      613,  613,  613,  613,  613,  613,  613,  613,  628,  615,
      616,  617,  616,  616,  616,  616,  616,  616,  616,  616,
      616,  616,  616,  616,  616,  616,  616,  616,  618,  619,
      620,  619,  619,  619,  619,  619,  619,  619,  619,  619,
      619,  619,  619,  619,  619,  619,  619,  621,  622,  623,
      622,  622,  622,  622,  622,  622,  622,  622,  622,  622,
      622,  622,  622,  622,  622,  622,  624,  625,  626,  625,
      625,  625,  625,  625,  625,  625,  625,  625,  625,  625,
      625,  625,  625,  625,  625,  627,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  628,

      616,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      616,  616,  616,  619,  619,  619,  619,  619,  619,  619,
      619,  619,  619,  619,  619,  619,  622,  622,  622,  622,
      622,  622,  622,  622,  622,  622,  622,  622,  622,  625,
      625,  625,  625,  625,  625,  625,  625,  625,  625,  625,
      625,  625,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      619,  619,  619,  619,  619,  619,  619,  619,  619,  622,
      622,  622,  622,  622,  622,  622,  622,  622,  625,  625,
      625,  625,  625,  625,  625,  625,  625,  613,  613,  613,

      613,  613,  613,  613,  613,  613,  613,  613,  613,  616,
      616,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      616,  619,  619,  619,  619,  619,  619,  619,  619,  619,
      619,  619,  619,  622,  622,  622,  622,  622,  622,  622,
      622,  622,  622,  622,  622,  625,  625,  625,  625,  625,
      625,  625,  625,  625,  625,  625,  625,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  616,  616,
      616,  616,  616,  616,  616,  616,  616,  616,  616,  619,
      619,  619,  619,  619,  619,  619,  619,  619,  619,  619,
      622,  622,  622,  622,  622,  622,  622,  622,  622,  622,

      622,  625,  625,  625,  625,  625,  625,  625,  625,  625,
      625,  625,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  616,  616,  616,  616,  616,  616,  616,  616,  616,
      619,  619,  619,  619,  619,  619,  619,  619,  619,  622,
      622,  622,  622,  622,  622,  622,  622,  622,  625,  625,
      625,  625,  625,  625,  625,  625,  625,  613,  613,  613,
      613,  613,  613,  613,  613,  616,  616,  616,  616,  616,
      616,  616,  616,  619,  619,  619,  619,  619,  619,  619,
      619,  622,  622,  622,  622,  622,  622,  622,  622,  625,
      625,  625,  625,  625,  625,  625,  625,  613,  613,  613,

      613,  613,  613,  613,  613,  616,  616,  616,  616,  616,
      616,  616,  616,  619,  619,  619,  619,  619,  619,  619,
      619,  622,  622,  622,  622,  622,  622,  622,  622,  625,
      625,  625,  625,  625,  625,  625,  625,  613,  613,  613,
      613,  613,  613,  613,  616,  616,  616,  616,  616,  616,
      616,  619,  619,  619,  619,  619,  619,  619,  622,  622,
      622,  622,  622,  622,  622,  625,  625,  625,  625,  625,
      625,  625,  613,  613,  613,  613,  616,  616,  616,  616,
      619,  619,  619,  619,  622,  622,  622,  622,  625,  625,
      625,  625,  613,  613,  616,  616,  619,  619,  622,  622,

      625,  625,  613,  616,  619,  622,  625,  613,  616,  619,
      622,  625,    0,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613
    } ;

static yyconst flex_int16_t yy_nxt[737] =
    {   0,
       12,   13,   14,   15,   12,   16,   17,   12,   18,   12,
       19,   12,   12,   12,   12,   20,   21,   12,   22,   12,
       12,   23,   24,   25,   26,   27,   28,  168,   29,   30,
       13,   14,   31,   30,   32,   33,   30,   34,   30,   35,
       30,   30,   30,   30,   36,   37,   30,   38,   30,   30,
       39,   40,   41,   42,   43,   28,  149,   44,   45,   13,
       14,   46,   45,   47,   48,   45,   49,   45,   50,   45,
       45,   45,   45,   51,   52,   45,   53,   45,   45,   54,
       55,   56,   57,   58,   28,  130,   59,   60,   13,   14,
       61,   60,   62,   63,   60,   64,   60,   65,   60,   60,

       60,   60,   66,   67,   60,   68,   60,   60,   69,   70,
       71,   72,   73,   28,  111,   74,   75,   13,   14,   76,
       75,   77,   78,   75,   79,   75,   80,   75,   75,   75,
       75,   81,   82,   75,   83,   75,   75,   84,   85,   86,
       87,   88,   28,  103,   89,   92,   92,   94,  106,   99,
       95,  100,  127,  108,  104,  109,  124,  107,  113,  113,
      115,  128,  120,  116,  121,  143,  101,  125,  132,  132,
      134,  146,  139,  135,  140,  162,  144,  151,  151,  122,
      147,  153,  165,  158,  154,  159,  163,  170,  170,  141,
      172,  166,  177,  173,  178,  181,  184,   92,   92,  108,

      160,  109,  113,  113,  303,  185,  182,  132,  132,  179,
      151,  151,  170,  170,  305,  315,  304,  317,  327,  612,
      329,  339,  611,  341,  351,  306,  307,  316,  318,  319,
      328,  330,  331,  340,  342,  343,  352,  353,  610,  609,
      608,  607,  606,  605,  604,  603,  602,  601,  354,  355,
       91,   91,  110,  110,  112,  112,  129,  129,  131,  131,
      148,  148,  150,  150,  167,  167,  169,  169,  186,  186,
      200,  200,  600,  599,  598,  597,  596,  595,  594,  593,
      592,  591,  590,  589,  588,  587,  586,  585,  584,  583,
      582,  581,  580,  579,  578,  577,  576,  575,  574,  573,

      572,  571,  570,  569,  568,  567,  566,  565,  564,  563,
      562,  561,  560,  559,  558,  557,  556,  555,  554,  553,
      552,  551,  550,  549,  548,  547,  546,  545,  544,  543,
      542,  541,  540,  539,  538,  537,  536,  535,  534,  533,
      532,  531,  530,  529,  528,  527,  526,  525,  524,  523,
      522,  521,  520,  519,  518,  517,  516,  515,  514,  513,
      512,  511,  510,  509,  508,  507,  506,  505,  504,  503,
      502,  501,  500,  499,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  486,  485,  484,  483,
      482,  481,  480,  479,  478,  477,  476,  475,  474,  473,

      472,  471,  470,  469,  468,  467,  466,  465,  464,  463,
      462,  461,  460,  459,  458,  457,  456,  455,  454,  453,
      452,  451,  450,  449,  448,  447,  446,  445,  444,  443,
      442,  441,  440,  439,  438,  437,  436,  435,  434,  433,
      432,  431,  430,  429,  428,  427,  426,  425,  424,  423,
      422,  421,  420,  419,  418,  417,  416,  415,  414,  413,
      412,  411,  410,  409,  408,  407,  406,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  391,  390,  389,  388,  387,  386,  385,  384,  383,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,

      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  356,  350,  349,  348,
      347,  346,  345,  344,  338,  337,  336,  335,  334,  333,
      332,  326,  325,  324,  323,  322,  321,  320,  314,  313,
      312,  311,  310,  309,  308,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  110,  252,  251,  250,  249,

      248,  247,  246,  245,  244,  243,  242,  241,  240,   91,
      110,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  227,   91,  110,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,   91,
      110,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,   91,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,   90,  110,
      183,  180,  176,  175,  174,  171,   91,  110,  164,  161,
      157,  156,  155,  152,   91,  110,  145,  142,  138,  137,
      136,  133,   91,  110,  126,  123,  119,  118,  117,  114,

       91,  105,  102,   98,   97,   96,   93,   90,  613,   11,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613
    } ;

static yyconst flex_int16_t yy_chk[737] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,  625,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    4,  622,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    6,  619,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    8,  616,    8,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   10,   25,   10,   17,   17,   19,   27,   23,
       19,   23,   43,   28,   25,   28,   41,   27,   33,   33,
       35,   43,   39,   35,   39,   56,   23,   41,   48,   48,
       50,   58,   54,   50,   54,   71,   56,   63,   63,   39,
       58,   65,   73,   69,   65,   69,   71,   78,   78,   54,
       80,   73,   84,   80,   84,   86,   88,   92,   92,  108,

       69,  108,  113,  113,  258,   88,   86,  132,  132,   84,
      151,  151,  170,  170,  259,  267,  258,  268,  276,  607,
      277,  285,  606,  286,  294,  259,  259,  267,  268,  268,
      276,  277,  277,  285,  286,  286,  294,  295,  605,  604,
      603,  601,  599,  597,  595,  593,  592,  589,  295,  295,
      614,  614,  615,  615,  617,  617,  618,  618,  620,  620,
      621,  621,  623,  623,  624,  624,  626,  626,  627,  627,
      628,  628,  588,  585,  584,  581,  580,  577,  576,  573,
      571,  570,  567,  566,  564,  563,  560,  559,  557,  556,
      553,  552,  550,  549,  546,  545,  543,  542,  539,  538,

      537,  536,  535,  534,  533,  531,  530,  529,  528,  527,
      526,  525,  523,  522,  521,  520,  519,  518,  517,  515,
      514,  513,  512,  511,  510,  509,  507,  506,  505,  504,
      503,  502,  501,  499,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  486,  485,  484,  483,
      482,  481,  480,  479,  478,  477,  476,  475,  474,  473,
      472,  471,  470,  469,  468,  467,  466,  465,  464,  463,
      462,  461,  460,  459,  458,  456,  455,  454,  453,  452,
      451,  450,  449,  447,  446,  445,  444,  443,  442,  441,
      440,  438,  437,  436,  435,  434,  433,  432,  431,  429,

      428,  427,  426,  425,  424,  423,  422,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  405,  404,  402,  401,  400,  399,  398,  397,  396,
      394,  393,  391,  390,  389,  388,  387,  386,  385,  383,
      382,  380,  379,  378,  377,  376,  375,  374,  372,  371,
      369,  368,  367,  366,  365,  364,  363,  361,  360,  358,
      357,  355,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  345,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  319,  318,  317,  316,  315,  314,

      313,  312,  311,  310,  309,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  293,  292,  291,
      290,  289,  288,  287,  284,  283,  282,  281,  280,  279,
      278,  275,  274,  273,  272,  271,  270,  269,  266,  265,
      264,  263,  262,  261,  260,  257,  256,  255,  254,  253,
      252,  251,  248,  247,  246,  244,  242,  241,  240,  239,
      238,  235,  234,  233,  231,  229,  228,  227,  226,  225,
      222,  221,  220,  218,  216,  215,  214,  213,  212,  209,
      208,  207,  205,  203,  202,  201,  199,  198,  195,  194,
      193,  191,  189,  188,  187,  186,  185,  184,  183,  182,

      181,  180,  179,  178,  175,  174,  173,  172,  171,  169,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  156,
      155,  154,  153,  152,  150,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  137,  136,  135,  134,  133,  131,
      129,  128,  127,  126,  125,  124,  123,  122,  121,  118,
      117,  116,  115,  114,  112,  107,  106,  105,  104,  103,
      102,  101,  100,   97,   96,   95,   94,   93,   90,   89,
       87,   85,   83,   82,   81,   79,   76,   74,   72,   70,
       68,   67,   66,   64,   61,   59,   57,   55,   53,   52,
       51,   49,   46,   44,   42,   40,   38,   37,   36,   34,

       31,   26,   24,   22,   21,   20,   18,   13,   11,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613,  613,  613,  613,  613,
      613,  613,  613,  613,  613,  613
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int libvma_yy_flex_debug;
int libvma_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *libvma_yytext;
/* Line 1 of config_scanner.l */
/*
 * Copyright (c) 2006 Mellanox Technologies Ltd. All rights reserved.
 *
 * This software is available to you under a choice of one of two
 * licenses.  You may choose to be licensed under the terms of the GNU
 * General Public License (GPL) Version 2, available from the file
 * COPYING in the main directory of this source tree, or the
 * OpenIB.org BSD license below:
 *
 *     Redistribution and use in source and binary forms, with or
 *     without modification, are permitted provided that the following
 *     conditions are met:
 *
 *      - Redistributions of source code must retain the above
 *        copyright notice, this list of conditions and the following
 *        disclaimer.
 *
 *      - Redistributions in binary form must reproduce the above
 *        copyright notice, this list of conditions and the following
 *        disclaimer in the documentation and/or other materials
 *        provided with the distribution.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * $Id: ibnl_scanner.ll,v 1.4 2005/02/23 21:08:37 eitan Exp $
 */
/* Line 36 of config_scanner.l */

//#define DEBUG 1  

#define yyparse libvma_yyparse
#define libvma_yylex   libvma_yylex
#define yyerror libvma_yyerror
#define yylval  libvma_yylval
#define yychar  libvma_yychar
#define yydebug libvma_yydebug
#define yynerrs libvma_yynerrs

#define libvma_yywrap  libvma_yywrap

#include <string.h>
#include <stdio.h>
#include "config_parser.h"
extern long __vma_config_line_num;
#define YY_NO_INPUT 1

/* Line 887 of config_scanner.c */

#define INITIAL 0
#define CANNAME 1
#define APP_ID_S1 2
#define APP_ID_S2 3
#define DAEMON_VALUE_S 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int libvma_yylex_destroy (void );

int libvma_yyget_debug (void );

void libvma_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE libvma_yyget_extra (void );

void libvma_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *libvma_yyget_in (void );

void libvma_yyset_in  (FILE * in_str  );

FILE *libvma_yyget_out (void );

void libvma_yyset_out  (FILE * out_str  );

yy_size_t libvma_yyget_leng (void );

char *libvma_yyget_text (void );

int libvma_yyget_lineno (void );

void libvma_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int libvma_yywrap (void );
#else
extern int libvma_yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( libvma_yytext, libvma_yyleng, 1, libvma_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( libvma_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( libvma_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, libvma_yyin))==0 && ferror(libvma_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(libvma_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int libvma_yylex (void);

#define YY_DECL int libvma_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after libvma_yytext and libvma_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( libvma_yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(libvma_yytext[libvma_yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! libvma_yyin )
			libvma_yyin = stdin;

		if ( ! libvma_yyout )
			libvma_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			libvma_yyensure_buffer_stack ();
			if ( yy_buffer_stack ) {
				YY_CURRENT_BUFFER_LVALUE =
					libvma_yy_create_buffer(libvma_yyin,YY_BUF_SIZE );
			}
		}

		libvma_yy_load_buffer_state( );
		}

	{
/* Line 57 of config_scanner.l */


/* Line 1033 of config_scanner.c */

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of libvma_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		/* coverity[var_deref_op] */
		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 614 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 710 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
/* Line 59 of config_scanner.l */
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
/* Line 61 of config_scanner.l */
{
	yylval.ival = APP_ID;
#ifdef DEBUG 
	printf("APP_ID\n");
#endif
	BEGIN(APP_ID_S1);
	return APP_ID;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
/* Line 70 of config_scanner.l */
{
	yylval.sval = (char *)malloc(strlen(libvma_yytext) + 1);
	strcpy(yylval.sval, libvma_yytext);
#ifdef DEBUG
	printf("PROGRAM:%s\n",yylval.sval);
#endif
	BEGIN(APP_ID_S2);
	return (PROGRAM);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
/* Line 80 of config_scanner.l */
{
	yylval.sval = (char *)malloc(strlen(libvma_yytext) + 1);
	strcpy(yylval.sval, libvma_yytext);
#ifdef DEBUG
	printf("USER_DEFINED_ID_STR:%s\n",yylval.sval);
#endif
	BEGIN(0);
	return (USER_DEFINED_ID_STR);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
/* Line 90 of config_scanner.l */
{ 
	yylval.ival = atoi(libvma_yytext);
#ifdef DEBUG
	printf("INT:%d\n",yylval.ival);
#endif
	return INT;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
/* Line 98 of config_scanner.l */
{
	yylval.ival = LOG;
#ifdef DEBUG
	printf("LOG\n");
#endif
	return LOG;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
/* Line 106 of config_scanner.l */
{
	yylval.ival = DEST;
#ifdef DEBUG
	printf("DEST\n");
#endif
	return DEST;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
/* Line 114 of config_scanner.l */
{
	yylval.ival = LEVEL;
#ifdef DEBUG
	printf("LEVEL\n");
#endif
	return LEVEL;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
/* Line 122 of config_scanner.l */
{
	yylval.ival = STDERR;
#ifdef DEBUG
	printf("STDERR\n");
#endif
	return STDERR;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
/* Line 130 of config_scanner.l */
{
	yylval.ival = SYSLOG;
#ifdef DEBUG
	printf("SYSLOG\n");
#endif
	return SYSLOG;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
/* Line 138 of config_scanner.l */
{
	yylval.ival = FILENAME;
#ifdef DEBUG
	printf("FILENAME\n");
#endif
	BEGIN(CANNAME);
	return FILENAME;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
/* Line 149 of config_scanner.l */
{
	yylval.ival = USE;
#ifdef DEBUG
	printf("USE\n");
#endif
	return USE;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
/* Line 157 of config_scanner.l */
{
	yylval.ival = TCP;
#ifdef DEBUG
	printf("TCP\n");
#endif
	return TCP;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
/* Line 165 of config_scanner.l */
{
	yylval.ival = UDP;
#ifdef DEBUG
	printf("UDP\n");
#endif
	return UDP;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
/* Line 173 of config_scanner.l */
{
	yylval.ival = OS;
#ifdef DEBUG
	printf("OS\n");
#endif
	return OS;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
/* Line 181 of config_scanner.l */
{
	yylval.ival = VMA;
#ifdef DEBUG
	printf("VMA\n");
#endif
	return VMA;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
/* Line 189 of config_scanner.l */
{
	yylval.ival = SDP;
#ifdef DEBUG
	printf("SDP\n");
#endif
	return SDP;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
/* Line 197 of config_scanner.l */
{
	yylval.ival = SA;
#ifdef DEBUG
	printf("SA\n");
#endif
	return SA;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
/* Line 205 of config_scanner.l */
{
	yylval.ival = TCP_CLIENT;
#ifdef DEBUG
	printf("TCP CLIENT\n");
#endif
	return TCP_CLIENT;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
/* Line 213 of config_scanner.l */
{
	yylval.ival = TCP_SERVER;
#ifdef DEBUG
	printf("TCP SERVER\n");
#endif
	return TCP_SERVER;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
/* Line 221 of config_scanner.l */
{
	yylval.ival = UDP_SENDER;
#ifdef DEBUG
	printf("UDP SENDER\n");
#endif
	return UDP_SENDER;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
/* Line 229 of config_scanner.l */
{
	yylval.ival = UDP_RECEIVER;
#ifdef DEBUG
	printf("UDP RECEIVER\n");
#endif
	return UDP_RECEIVER;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
/* Line 237 of config_scanner.l */
{
	yylval.ival = UDP_CONNECT;
#ifdef DEBUG
	printf("UDP CONNECT\n");
#endif
	return UDP_CONNECT;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
/* Line 245 of config_scanner.l */
{
	yylval.sval = (char *)malloc(strlen(libvma_yytext) + 1);
	strcpy(yylval.sval, libvma_yytext);
#ifdef DEBUG
	printf("NAME:%s\n",yylval.sval);
#endif
	BEGIN(0);
	return (NAME);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
/* Line 255 of config_scanner.l */
{
	yylval.ival = DAEMON_KEY;
#ifdef DEBUG
	printf("DAEMON_KEY\n");
#endif
	BEGIN(DAEMON_VALUE_S);
	return DAEMON_KEY;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
/* Line 264 of config_scanner.l */
{
	yylval.sval = (char *)malloc(strlen(libvma_yytext) + 1);
	strcpy(yylval.sval, libvma_yytext);
#ifdef DEBUG
	printf("DAEMON_VALUE:%s\n",yylval.sval);
#endif
	BEGIN(0);
	return (DAEMON_VALUE);
}
	YY_BREAK
case 27:
/* rule 25 can match eol */
YY_RULE_SETUP
/* Line 274 of config_scanner.l */
{
	__vma_config_line_num++;
#ifdef DEBUG
	printf("LINE\n");
#endif
	yylval.ival = LINE;
	return(LINE);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
/* Line 283 of config_scanner.l */
{
 	__vma_config_line_num++;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
/* Line 287 of config_scanner.l */
{}
	YY_BREAK
case 30:
YY_RULE_SETUP
/* Line 289 of config_scanner.l */
{
#ifdef DEBUG
	printf("CHAR:%c\n",libvma_yytext[0]);
#endif
	return(libvma_yytext[0]);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
/* Line 296 of config_scanner.l */
ECHO;
	YY_BREAK
/* Line 1492 of config_scanner.c */
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CANNAME):
case YY_STATE_EOF(APP_ID_S1):
case YY_STATE_EOF(APP_ID_S2):
case YY_STATE_EOF(DAEMON_VALUE_S):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed libvma_yyin at a new source and called
			 * libvma_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = libvma_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( libvma_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * libvma_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of libvma_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					libvma_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			libvma_yyrestart(libvma_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) libvma_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 614 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 614 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 613);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					libvma_yyrestart(libvma_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( libvma_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve libvma_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void libvma_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        libvma_yyensure_buffer_stack ();
		if ( yy_buffer_stack ) {
			YY_CURRENT_BUFFER_LVALUE =
            			libvma_yy_create_buffer(libvma_yyin,YY_BUF_SIZE );
		}
	}

	libvma_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	libvma_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void libvma_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		libvma_yypop_buffer_state();
	 *		libvma_yypush_buffer_state(new_buffer);
     */
	libvma_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( yy_buffer_stack ) {
		YY_CURRENT_BUFFER_LVALUE = new_buffer;
	}
	libvma_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (libvma_yywrap()) processing, but the only time this flag
	 * is looked at is after libvma_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void libvma_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	libvma_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE libvma_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) libvma_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in libvma_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) libvma_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in libvma_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	libvma_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with libvma_yy_create_buffer()
 * 
 */
    void libvma_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		libvma_yyfree((void *) b->yy_ch_buf  );

	libvma_yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a libvma_yyrestart() or at EOF.
 */
    static void libvma_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	libvma_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then libvma_yy_init_buffer was _probably_
     * called from libvma_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void libvma_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		libvma_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void libvma_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	libvma_yyensure_buffer_stack();

	/* This block is copied from libvma_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER) {
		(yy_buffer_stack_top)++;
	}
	if (yy_buffer_stack) {
		YY_CURRENT_BUFFER_LVALUE = new_buffer;
	}

	/* copied from libvma_yy_switch_to_buffer. */
	libvma_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void libvma_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	libvma_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		libvma_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void libvma_yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)libvma_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in libvma_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)libvma_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in libvma_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE libvma_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) libvma_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in libvma_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	libvma_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to libvma_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       libvma_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE libvma_yy_scan_string (yyconst char * yystr )
{
    
	return libvma_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to libvma_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE libvma_yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) libvma_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in libvma_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = libvma_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in libvma_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up libvma_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		libvma_yytext[libvma_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = libvma_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		libvma_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int libvma_yyget_lineno  (void)
{
        
    return libvma_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *libvma_yyget_in  (void)
{
        return libvma_yyin;
}

/** Get the output stream.
 * 
 */
FILE *libvma_yyget_out  (void)
{
        return libvma_yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t libvma_yyget_leng  (void)
{
        return libvma_yyleng;
}

/** Get the current token.
 * 
 */

char *libvma_yyget_text  (void)
{
        return libvma_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void libvma_yyset_lineno (int  line_number )
{
    
    libvma_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see libvma_yy_switch_to_buffer
 */
void libvma_yyset_in (FILE *  in_str )
{
        libvma_yyin = in_str ;
}

void libvma_yyset_out (FILE *  out_str )
{
        libvma_yyout = out_str ;
}

int libvma_yyget_debug  (void)
{
        return libvma_yy_flex_debug;
}

void libvma_yyset_debug (int  bdebug )
{
        libvma_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from libvma_yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    libvma_yyin = stdin;
    libvma_yyout = stdout;
#else
    libvma_yyin = (FILE *) 0;
    libvma_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * libvma_yylex_init()
     */
    return 0;
}

/* libvma_yylex_destroy is for both reentrant and non-reentrant scanners. */
int libvma_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		libvma_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		libvma_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	libvma_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * libvma_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *libvma_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *libvma_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void libvma_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see libvma_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

/* Line 296 of config_scanner.l */



int libvma_yywrap ()
{
	return (1);
}


